# Generated by Django 4.0.3 on 2022-10-10 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeCode', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeCode', models.CharField(max_length=50)),
                ('stop', models.CharField(max_length=100)),
                ('preferences', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopAddress', models.CharField(max_length=100)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopHopperAPI.route')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=50)),
                ('stopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopHopperAPI.stops')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriveBy', models.CharField(blank=True, max_length=20)),
                ('priority', models.IntegerField(blank=True)),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopHopperAPI.stops')),
            ],
        ),
    ]
