# Generated by Django 4.0.3 on 2022-10-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stopHopperAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteCodes',
        ),
        migrations.AlterModelTable(
            name='preferences',
            table='Preferences',
        ),
        migrations.AlterModelTable(
            name='route',
            table='Route',
        ),
        migrations.AlterModelTable(
            name='stops',
            table='Stops',
        ),
        migrations.AlterModelTable(
            name='tasks',
            table='Tasks',
        ),
    ]
