# Generated by Django 4.0.3 on 2022-10-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopHopperAPI', '0002_alter_route_routecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='routeCode',
            field=models.CharField(default='9Enoqm', max_length=6, unique=True),
        ),
    ]
